DROP TABLE IF EXISTS course;
DROP TABLE IF EXISTS groups CASCADE;
DROP TABLE IF EXISTS lecture;
DROP TABLE IF EXISTS room;
DROP TABLE IF EXISTS student;
DROP TABLE IF EXISTS teacher;

CREATE TABLE course(id LONG AUTO_INCREMENT PRIMARY KEY, name VARCHAR, level INTEGER, hours INTEGER);
CREATE TABLE groups(id LONG AUTO_INCREMENT PRIMARY KEY, name VARCHAR);
CREATE TABLE lecture(id LONG AUTO_INCREMENT PRIMARY KEY, name VARCHAR, number INTEGER);
CREATE TABLE room(id LONG AUTO_INCREMENT PRIMARY KEY, name VARCHAR, capacity INTEGER);
CREATE TABLE student(id LONG AUTO_INCREMENT PRIMARY KEY, name VARCHAR, surname VARCHAR, academicYear INTEGER, groupId LONG, CONSTRAINT fk_group FOREIGN KEY(groupId) REFERENCES groups(id));
CREATE TABLE teacher(id LONG AUTO_INCREMENT PRIMARY KEY, name VARCHAR, surname VARCHAR, category VARCHAR, hours INTEGER);